### ISSUE TITLE
⚡️Add Export Button

### ISSUE THREAD

**Issue by PrerakMathur20** [iiitl/geet-hub-editor#1]
⚡️Add Export Button
---

Add an _Export_ or _Download_ Button for the final edited audio file to be saved on the `/edit` page.

**Comment by SahilSingh177** [comment]
Please Assign this to Me.

**Comment by PrerakMathur20** [comment]
@SahilSingh177 
To give a fair opportunity to everyone, issues are assigned on one after one basis. As since, you've already been assigned another issue, kindly complete that one, to get another issue assigned.

**Comment by ghost** [comment]
Can I be assigned this issue?
