### ISSUE TITLE
🗞 Add Setup section to README.md file

### ISSUE THREAD

**Issue by PrerakMathur20** [iiitl/geet-hub-editor#2]
📄 Add Setup section to README.md file
---

To allow easy setup of the project, create a **Setup** section in the `README.md` file and add steps on how locally allow the setup of the project.

The _Setup_ Section must include the following -

* Create a Fork
* `git clone` the project
* Check for Prerequisites for the project
* Commands for Initiating and running the project

**Comment by KanishkDadhich** [comment]
Hey @PrerakMathur20 . I would like to work on this issue.
Could you please assign this to me.

**Comment by deep-69bits** [comment]
Can I??

**Comment by PrerakMathur20** [comment]
@KanishkDadhich Assigned to you!

@deep-69bits @Nincompup Assigned to you!

@KanishkDadhich Since the Issues are FCFS, I can't assign you this one. Feel free to look around for more issues you're comfortable with.
