### ISSUE TITLE
Adding route Protection

### ISSUE THREAD

**Issue by KarthikS373** [iiitl/geet-hub-editor#24]
Issue:
It is noted that user can route to the editor page without actually uploading a audio file.

Fixes:
- Adding a default audio file
- Adding route protection so that user is redirected back to homepage when trying to route manually

Supporting docs:
[Screencast from 10-10-22 03:17:16 PM IST.webm](https://user-images.githubusercontent.com/96634646/194839710-85ec9da0-d238-45c0-8f42-1805db23ebfd.webm)

**Comment by PrerakMathur20** [comment]
@KarthikS373 
Would you like to work on this issue?

**Comment by KarthikS373** [comment]
>@KarthikS373
Would you like to work on this issue?

yes please I would like to take this up
