### ISSUE TITLE
Creating a login model where each user can save the files on the cloud.

### ISSUE THREAD

**Issue by SahilSingh177** [iiitl/geet-hub-editor#25]
# Issue: 
 In the Edit Page, the audio file disappears on reloading the page. Hence, the user has to re-upload the music file.

https://user-images.githubusercontent.com/96344003/194947135-3be4af5a-3e71-4eff-9fac-30457707fdea.mov

# Fix: 
Using Firebase's cloud storage, so that the audio file remains present even on reloading the page.

**Comment by PrerakMathur20** [comment]
Duplicate #21
---

Kindly resume this discussion and solution in the old issue.
