### ISSUE TITLE
⚡️Add Labels to Zoom and Volume Sliders

### ISSUE THREAD

**Issue by PrerakMathur20** [iiitl/geet-hub-editor#3]
⚡️Add Labels to _Zoom_ and _Volume_ Sliders
---

The sliders don't visibly explain their purpose, and hence need labels on them.
Add a _Zoom_ label under Slider 1.
Add a _Volume_ label under Slider 2.

**Comment by superiorsd10** [comment]
I would like to work on this issue. Can you please assign It to me?

**Comment by PrerakMathur20** [comment]
@superiorsd10 
To give a fair opportunity to everyone, issues are assigned on one after one basis. As since, you've already been assigned another issue, kindly complete that one, to get more issues assigned.

**Comment by SahilSingh177** [comment]
Please assign this issue to me.
