### ISSUE TITLE
⚡️Change Slider's Intensity

### ISSUE THREAD

**Issue by PrerakMathur20** [iiitl/geet-hub-editor#5]
⚡️Change Slider's Intensity 
---
The _Zoom_ and _Volume_ sliders are set up go from 0% to 500%.
Change the maximum intensity to go only as high as 125% for both _Zoom_ and _Volume_.

**Comment by superiorsd10** [comment]
I would like to work on this issue. Can you please assign it to me?

**Comment by PrerakMathur20** [comment]
@superiorsd10 
To give a fair opportunity to everyone, issues are assigned on one after one basis. As since, you've already been assigned another issue, kindly complete that one, to get more issues assigned.

**Comment by KarthikS373** [comment]
I would like to work on this issue. Please assign this to me...

**Comment by PrerakMathur20** [comment]
@KarthikS373 Any Updates?

**Comment by PrerakMathur20** [comment]
Assigned to @pranjalad12
