### ISSUE TITLE
⚡️ Add toggle functionality

### ISSUE THREAD

**Issue by PrerakMathur20** [iiitl/geet-hub-editor#6]
⚡️ Add toggle functionality
---

The toggle button for **Mono** and **Dual** audio isn't functional due to some underlying bugs. Find and fix the bug to implement this feature.

<img width="138" alt="Screenshot 2022-09-30 at 7 50 18 PM" src="https://user-images.githubusercontent.com/76054330/193290534-a9507049-9832-4426-ab46-17cfbd51c484.png">

**Comment by ghost** [comment]
Can I work on this issue?
