### ISSUE TITLE
📄 Add CODE_OF_CONDUCT.md file

### ISSUE THREAD

**Issue by PrerakMathur20** [iiitl/geet-hub-editor#7]
📄 Add CODE_OF_CONDUCT.md file
---

Add a CODE_OF_CONDUCT.md file to the root of the project.

**Comment by Nincompup** [comment]
Hello, could you assign this issue to me ?

**Comment by KanishkDadhich** [comment]
Hello @PrerakMathur20 .
I would like to work on this issue. Could you please assign it to me.

**Comment by PrerakMathur20** [comment]
@Nincompup Assigned to you!

@KanishkDadhich Since the Issues are FCFS, I can't assign you this one. Feel free to look around for more issues you're comfortable with.
